<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class InsertCountriesCodeMasterTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::insert("INSERT INTO `code_master` (`codeType`, `codeValue`) VALUES
            ('countries', 'Abkhazia'),
            ('countries', 'Afghanistan'),
            ('countries', 'Akrotiri and Dhekelia'),
            ('countries', 'Aland'),
            ('countries', 'Albania'),
            ('countries', 'Algeria'),
            ('countries', 'American Samoa'),
            ('countries', 'Andorra'),
            ('countries', 'Angola'),
            ('countries', 'Anguilla'),
            ('countries', 'Antigua and Barbuda'),
            ('countries', 'Argentina'),
            ('countries', 'Armenia'),
            ('countries', 'Aruba'),
            ('countries', 'Ascension Island'),
            ('countries', 'Australia'),
            ('countries', 'Austria'),
            ('countries', 'Azerbaijan'),
            ('countries', 'Bahamas, The'),
            ('countries', 'Bahrain'),
            ('countries', 'Bangladesh'),
            ('countries', 'Barbados'),
            ('countries', 'Belarus'),
            ('countries', 'Belgium'),
            ('countries', 'Belize'),
            ('countries', 'Benin'),
            ('countries', 'Bermuda'),
            ('countries', 'Bhutan'),
            ('countries', 'Bolivia'),
            ('countries', 'Bosnia and Herzegovina'),
            ('countries', 'Botswana'),
            ('countries', 'Brazil'),
            ('countries', 'Brunei'),
            ('countries', 'Bulgaria'),
            ('countries', 'Burkina Faso'),
            ('countries', 'Burundi'),
            ('countries', 'Cambodia'),
            ('countries', 'Cameroon'),
            ('countries', 'Canada'),
            ('countries', 'Cape Verde'),
            ('countries', 'Cayman Islands'),
            ('countries', 'Central Africa Republic'),
            ('countries', 'Chad'),
            ('countries', 'Chile'),
            ('countries', 'China'),
            ('countries', 'Christmas Island'),
            ('countries', 'Cocos (Keeling) Islands'),
            ('countries', 'Colombia'),
            ('countries', 'Comoros'),
            ('countries', 'Congo'),
            ('countries', 'Cook Islands'),
            ('countries', 'Costa Rica'),
            ('countries', 'Cote d lvoire'),
            ('countries', 'Croatia'),
            ('countries', 'Cuba'),
            ('countries', 'Cyprus'),
            ('countries', 'Czech Republic'),
            ('countries', 'Denmark'),
            ('countries', 'Djibouti'),
            ('countries', 'Dominica'),
            ('countries', 'Dominican Republic'),
            ('countries', 'East Timor Ecuador'),
            ('countries', 'Egypt'),
            ('countries', 'El Salvador'),
            ('countries', 'Equatorial Guinea'),
            ('countries', 'Eritrea'),
            ('countries', 'Estonia'),
            ('countries', 'Ethiopia'),
            ('countries', 'Falkland Islands'),
            ('countries', 'Faroe Islands'),
            ('countries', 'Fiji'),
            ('countries', 'Finland'),
            ('countries', 'France'),
            ('countries', 'French Polynesia'),
            ('countries', 'Gabon'),
            ('countries', 'Cambia'),
            ('countries', 'Georgia'),
            ('countries', 'Germany'),
            ('countries', 'Ghana'),
            ('countries', 'Gibraltar'),
            ('countries', 'Greece'),
            ('countries', 'Greenland'),
            ('countries', 'Grenada'),
            ('countries', 'Guam'),
            ('countries', 'Guatemala'),
            ('countries', 'Guemsey'),
            ('countries', 'Guinea'),
            ('countries', 'Guinea-Bissau'),
            ('countries', 'Guyana'),
            ('countries', 'Haiti'),
            ('countries', 'Honduras'),
            ('countries', 'Hong Kong'),
            ('countries', 'Hungary'),
            ('countries', 'Iceland'),
            ('countries', 'Indonesia'),
            ('countries', 'Iran'),
            ('countries', 'Iraq'),
            ('countries', 'Ireland'),
            ('countries', 'Isle of Man'),
            ('countries', 'Israel'),
            ('countries', 'Italy'),
            ('countries', 'Jamaica'),
            ('countries', 'Japan'),
            ('countries', 'Jersey'),
            ('countries', 'Jordan'),
            ('countries', 'Kazakhstan'),
            ('countries', 'Kenya'),
            ('countries', 'Kiribati'),
            ('countries', 'Korea, N'),
            ('countries', 'Korea, S'),
            ('countries', 'Kosovo'),
            ('countries', 'Kuwait'),
            ('countries', 'Kyrgyzstan'),
            ('countries', 'Laos'),
            ('countries', 'Latvia'),
            ('countries', 'Lebanon'),
            ('countries', 'Lesotho'),
            ('countries', 'Liberia'),
            ('countries', 'Libya'),
            ('countries', 'Liechtenstein'),
            ('countries', 'Lithuania'),
            ('countries', 'Luxembourg'),
            ('countries', 'Macao'),
            ('countries', 'Macedonia'),
            ('countries', 'Madagascar'),
            ('countries', 'Malawi'),
            ('countries', 'Malaysia'),
            ('countries', 'Maldives'),
            ('countries', 'Mali'),
            ('countries', 'Malta'),
            ('countries', 'Marshall Islands'),
            ('countries', 'Mauritania'),
            ('countries', 'Mauritius'),
            ('countries', 'Mayotte'),
            ('countries', 'Mexico'),
            ('countries', 'Micronesia'),
            ('countries', 'Moldova'),
            ('countries', 'Monaco'),
            ('countries', 'Mongolia'),
            ('countries', 'Montenegro'),
            ('countries', 'Montserrat'),
            ('countries', 'Morocco'),
            ('countries', 'Mozambique'),
            ('countries', 'Myanmar'),
            ('countries', 'Nagorno-Karabakh'),
            ('countries', 'Namibia'),
            ('countries', 'Nauru'),
            ('countries', 'Nepal'),
            ('countries', 'Netherlands'),
            ('countries', 'Netherlands Antilles'),
            ('countries', 'New Caledonia'),
            ('countries', 'New Zealand'),
            ('countries', 'Nicaragua'),
            ('countries', 'Niger'),
            ('countries', 'Nigeria'),
            ('countries', 'Niue'),
            ('countries', 'Norfolk Island'),
            ('countries', 'Northern Cyprus'),
            ('countries', 'Northern Mariana Islands'),
            ('countries', 'Norway'),
            ('countries', 'Oman'),
            ('countries', 'Pakistan'),
            ('countries', 'Palau'),
            ('countries', 'Palestine'),
            ('countries', 'Panama'),
            ('countries', 'Papua New Guinea'),
            ('countries', 'Paraguay'),
            ('countries', 'Peru'),
            ('countries', 'Philippines'),
            ('countries', 'Pitcaim Islands'),
            ('countries', 'Poland'),
            ('countries', 'Portugal'),
            ('countries', 'Puerto Rico'),
            ('countries', 'Qatar'),
            ('countries', 'Romania'),
            ('countries', 'Russia'),
            ('countries', 'Rwanda'),
            ('countries', 'Sahrawi Arab Democratic Republic'),
            ('countries', 'Saint-Barthelemy'),
            ('countries', 'Saint Helena'),
            ('countries', 'Saint Kitts and Nevis'),
            ('countries', 'Saint Lucia'),
            ('countries', 'Saint Martin'),
            ('countries', 'Saint Pierre and Miquelon'),
            ('countries', 'Saint Vincent and Grenadines'),
            ('countries', 'Samos'),
            ('countries', 'San Marino'),
            ('countries', 'Sao Tome and Principe'),
            ('countries', 'Saudi Arabia'),
            ('countries', 'Senegal'),
            ('countries', 'Serbia'),
            ('countries', 'Seychelles'),
            ('countries', 'Sierra Leone'),
            ('countries', 'Singapore'),
            ('countries', 'Slovakia'),
            ('countries', 'Slovenia'),
            ('countries', 'Solomon Islands'),
            ('countries', 'Somalia'),
            ('countries', 'Somaliland'),
            ('countries', 'South Africa'),
            ('countries', 'South Ossetia'),
            ('countries', 'Spain'),
            ('countries', 'Sri Lanka'),
            ('countries', 'Sudan'),
            ('countries', 'Suriname'),
            ('countries', 'Svalbard'),
            ('countries', 'Swaziland'),
            ('countries', 'Sweden'),
            ('countries', 'Switzerland'),
            ('countries', 'Syria'),
            ('countries', 'Tajikistan'),
            ('countries', 'Tanzania'),
            ('countries', 'Thailand'),
            ('countries', 'Togo'),
            ('countries', 'Tokelau'),
            ('countries', 'Tonga'),
            ('countries', 'Transnistria'),
            ('countries', 'Trinidad and Tobago'),
            ('countries', 'Tristan da Cunha'),
            ('countries', 'Tunisia'),
            ('countries', 'Turkey'),
            ('countries', 'Turkmenistan'),
            ('countries', 'Turks and Caicos Islands'),
            ('countries', 'Tuvalu'),
            ('countries', 'Uganda'),
            ('countries', 'Ukraine'),
            ('countries', 'United Arab Emirates'),
            ('countries', 'United Kingdom'),
            ('countries', 'United States'),
            ('countries', 'Uruguay'),
            ('countries', 'Uzbekistan'),
            ('countries', 'Vanuatu'),
            ('countries', 'Vatican City'),
            ('countries', 'Venezuela'),
            ('countries', 'Vietnam'),
            ('countries', 'Virgin Islands, British'),
            ('countries', 'Virgin Islands, U.S.'),
            ('countries', 'Wallis and Futuna'),
            ('countries', 'Yemen'),
            ('countries', 'Zambia'),
            ('countries', 'Zimbabwe'),
            ('countries', 'India'),
            ('countries', 'Dubai'),
            ('countries', 'Taiwan')
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {        
        
    }
}
